In [4]:
import numpy as np


In [3]:
myList = [1,2,3]
np.array(myList)


array([1, 2, 3])

In [7]:
m = np.array([[1,2,3],[4,5,6]])
m
m.shape

(2, 3)

In [11]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
n = np.linspace(0,4,9)

In [13]:
n

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

in linspace- we tell how many elements we want ex: np.linspace(0,4,9), we want  9 elements from 0 to 4 

in arange - we tell range, with increment, for ex: np.arange(0,30,2)- from 0 to 30, evenly (2) incremented values

In [16]:
n.resize(3,3)
n

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [23]:
o = np.linspace(0,4,9)
o
o.shape


(9,)

In [24]:
n = np.arange(13)**2

In [25]:
n

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [26]:
n[0:3]

array([0, 1, 4])

In [27]:
n[-1]

144

In [28]:
n.resize(3,4)

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [29]:
m = np.arange(0,30,2)

In [30]:
m.shape

(15,)

In [31]:
m.resize(3,3)

In [32]:
m

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [33]:
m[0:3]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [34]:
m[:2]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [35]:
m[:,2]

array([ 4, 10, 16])

In [36]:
m[2,:]

array([12, 14, 16])

In [37]:
m = np.arange(36)

In [38]:
m.resize(6,6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
m[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [40]:
m[2,2]

14

In [41]:
m[[2,2],[2,3]]

array([14, 15])

In [42]:
m[[2,2],[2,3],[3,2],[3,3]]

IndexError: too many indices for array

In [43]:
m[-1,::2]

array([30, 32, 34])

In [44]:
m[m>30]

array([31, 32, 33, 34, 35])

In [5]:
import pandas as pd
pd.Series?


In [47]:
animals = ['tiger',"dog", "mouse"]

In [48]:
pd.Series(animals)

0    tiger
1      dog
2    mouse
dtype: object

In [50]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

In [51]:
df

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [56]:
df['Item Purchased']

Store 1        Dog Food
Store 1    Kitty Litter
Store 2       Bird Seed
Name: Item Purchased, dtype: object

In [57]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


In [58]:
df

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0      Bird Seed  Vinod

In [59]:
df['Cost'] = df['Cost'] * 0.2

In [60]:
df


Cost Item Purchased   Name
Store 1   4.5       Dog Food  Chris
Store 1   0.5   Kitty Litter  Kevyn
Store 2   1.0      Bird Seed  Vinod

In [61]:
df['Cost']*0.2

Store 1    0.9
Store 1    0.1
Store 2    0.2
Name: Cost, dtype: float64

In [62]:
df


Cost Item Purchased   Name
Store 1   4.5       Dog Food  Chris
Store 1   0.5   Kitty Litter  Kevyn
Store 2   1.0      Bird Seed  Vinod

In [63]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])


df['Store'] = df.index

In [64]:
df

Cost Item Purchased   Name    Store
Store 1  22.5       Dog Food  Chris  Store 1
Store 1   2.5   Kitty Litter  Kevyn  Store 1
Store 2   5.0      Bird Seed  Vinod  Store 2

In [69]:
df = df.set_index([df.index, 'Name'])
df.index.names = ['Location', 'Name']
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))
df

KeyError: 'Name'

In [66]:
df

Cost Item Purchased    Store
        Name                               
Store 1 Chris  22.5       Dog Food  Store 1
        Kevyn   2.5   Kitty Litter  Store 1
Store 2 Vinod   5.0      Bird Seed  Store 2

In [73]:
df = ('A','B','C','D','E','F')

In [74]:
df

('A', 'B', 'C', 'D', 'E', 'F')

In [75]:
df[1]

'B'

In [77]:
df = pd.DataFrame(["Purchase1","Purchase2","Purchase3"], index=['Store1','Store2','Store3'])

In [78]:
df

0
Store1  Purchase1
Store2  Purchase2
Store3  Purchase3

In [79]:
df.append(["Cost1","Cost2","Cost3"])

0
Store1  Purchase1
Store2  Purchase2
Store3  Purchase3
0           Cost1
1           Cost2
2           Cost3

In [80]:
purchase_1 = pd.Series({'Name':'Sri',"Cost": 20.5,"Item": "Dog food"})

In [81]:
purchase_2 = pd.Series({'Name':'Sasi',"Cost": 5.5,"Item": "Tiger food"})

In [82]:
purchase_3 = pd.Series({'Name':'Shriya',"Cost": 4.5,"Item": "rest food"})

In [84]:
df = pd.DataFrame([purchase_1,purchase_2,purchase_3], index=("Store1","Store2","Store3"))

In [85]:
df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [86]:
df.loc('Store2')

In [87]:
df.loc['Store2']

Cost           5.5
Item    Tiger food
Name          Sasi
Name: Store2, dtype: object

In [88]:
df.iloc['Store2']

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [Store2] of <class 'str'>

In [89]:
df.iloc[0]

Cost        20.5
Item    Dog food
Name         Sri
Name: Store1, dtype: object

In [90]:
df.index

Index(['Store1', 'Store2', 'Store3'], dtype='object')

In [91]:
df.values

array([[20.5, 'Dog food', 'Sri'],
       [5.5, 'Tiger food', 'Sasi'],
       [4.5, 'rest food', 'Shriya']], dtype=object)

In [92]:
df.iloc[2]

Cost          4.5
Item    rest food
Name       Shriya
Name: Store3, dtype: object

In [93]:
df.iloc[1]

Cost           5.5
Item    Tiger food
Name          Sasi
Name: Store2, dtype: object

In [94]:
df.loc['Store1','Cost']

20.5

In [95]:
df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [96]:
df.T

Store1      Store2     Store3
Cost      20.5         5.5        4.5
Item  Dog food  Tiger food  rest food
Name       Sri        Sasi     Shriya

In [97]:
df.loc["Store1"]

Cost        20.5
Item    Dog food
Name         Sri
Name: Store1, dtype: object

In [98]:
df.loc['Cost']

KeyError: 'the label [Cost] is not in the [index]'

In [99]:
df.iloc[0]

Cost        20.5
Item    Dog food
Name         Sri
Name: Store1, dtype: object

In [100]:
df.T


Store1      Store2     Store3
Cost      20.5         5.5        4.5
Item  Dog food  Tiger food  rest food
Name       Sri        Sasi     Shriya

In [101]:
df.T.loc['Cost']

Store1    20.5
Store2     5.5
Store3     4.5
Name: Cost, dtype: object

In [102]:
df.T.iloc[1]

Store1      Dog food
Store2    Tiger food
Store3     rest food
Name: Item, dtype: object

In [103]:
df.loc['Store1']['Cost']

20.5

In [104]:
df


Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [105]:
df[:,["Cost","Name"]]

TypeError: unhashable type: 'slice'

In [106]:
df.loc[:,["Name","Cost"]]

Name  Cost
Store1     Sri  20.5
Store2    Sasi   5.5
Store3  Shriya   4.5

In [107]:
df.drop('Store1')

Cost        Item    Name
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [108]:
df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [111]:
copy_df = df.copy()

In [112]:
copy_df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [113]:
copy_df.drop('Store1')

Cost        Item    Name
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [114]:
df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [115]:
copy_df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [116]:
del copy_df['Name']

In [117]:
copy_df

Cost        Item
Store1  20.5    Dog food
Store2   5.5  Tiger food
Store3   4.5   rest food

In [118]:
df

Cost        Item    Name
Store1  20.5    Dog food     Sri
Store2   5.5  Tiger food    Sasi
Store3   4.5   rest food  Shriya

In [119]:
df2 = df

In [120]:
del df2['Cost']

In [121]:
df

Item    Name
Store1    Dog food     Sri
Store2  Tiger food    Sasi
Store3   rest food  Shriya

In [122]:
df2

Item    Name
Store1    Dog food     Sri
Store2  Tiger food    Sasi
Store3   rest food  Shriya

In [123]:
df['Location'] = None

In [124]:
df

Item    Name Location
Store1    Dog food     Sri     None
Store2  Tiger food    Sasi     None
Store3   rest food  Shriya     None

In [ ]:
df.set_index(["Item", "Name"])

In [ ]:
df

In [7]:
df = pd.DataFrame({'month': [1, 4, 7, 10],'year': [2012, 2014, 2013, 2014],'sale':[55, 40, 84, 31]})

In [8]:
df

month  sale  year
0      1    55  2012
1      4    40  2014
2      7    84  2013
3     10    31  2014

In [9]:
df.set_index(["month", "sale"])

year
month sale      
1     55    2012
4     40    2014
7     84    2013
10    31    2014

In [10]:
df.reset_index()

index  month  sale  year
0      0      1    55  2012
1      1      4    40  2014
2      2      7    84  2013
3      3     10    31  2014